name: update-readme

# author: @MikeRalphson
# based on https://github.com/victoriadrake/victoriadrake/blob/master/.github/workflows/update.yaml

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 23 * * *'
  workflow_dispatch: {}
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 🍽️ Get working copy
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: 🍳 Shake & bake README
        run: |
          npm i
          node ./scripts/update.js ${{ secrets.GITHUB_TOKEN }}
      - name: 🚀 Deploy
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add .
          git diff-index --quiet HEAD || git commit -am "Update dynamic content"
          git push --all -f https://${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git
